import { createContext, useContext, useState, type ReactNode } from 'react'
import { mergeSurveyTranslations } from '../data/surveyTranslations'

export type Lang = 'ES' | 'EN' | 'KO' | 'ZH'

const langs: Lang[] = ['ES', 'EN', 'KO', 'ZH']

const dict: Record<Lang, Record<string, string>> = {
  ES: {
    // Nav
    'nav.como-funciona': 'Cómo funciona',
    'nav.servicios': 'Servicios',
    'nav.demos': 'Demos',
    'nav.proyectos': 'Proyectos',
    'nav.precios': 'Precios',
    'nav.contacto': 'Contacto',
    'nav.inicio': 'Inicio',
    'nav.agendar': 'Agendar cita',
    'nav.competencias': 'Competencias',
    'theme.dark': 'Oscuro',
    'theme.light': 'Claro',

    // Hero
    'hero.titulo1': 'Tu negocio puede',
    'hero.titulo2': 'trabajar solo.',
    'hero.sub': 'Nosotros conectamos tus citas, ventas y operación en un solo sistema. Tú dejas de hacer todo a mano. Tu negocio empieza a fluir.',
    'hero.btn1': 'Ver cómo funciona',
    'hero.btn2': 'Hablar por WhatsApp',
    'hero.floating': 'vanity academy · dashboard · ia survey',
    'hero.img.soul23': 'soul:23',
    'hero.img.cursos': 'Cursos de Vanity Academy',
    'hero.img.dashboard': 'Dashboard visual de operación',
    'hero.img.sitio': 'Sitio de Dra. DFG',
    'hero.img.reporte': 'Reporte de encuestas con IA',

    // Section2Problem
    'problem.titulo': '¿Te pasa que…',
    'problem.sub': 'No estás solo. La mayoría de negocios en México operan así:',
    'problem.1': 'Estás todo el día respondiendo mensajes para agendar citas',
    'problem.2': 'Haces cuentas a mano para saber cuánto vendiste',
    'problem.3': 'No sabes qué pasa en tu negocio si no estás ahí',
    'problem.4': 'Tus empleados llegan tarde y no hay registro de nada',
    'problem.5': 'Los clientes cancelan y no tienes control',
    'problem.cta': 'Eso se puede cambiar. Y no es tan complicado como crees.',
    'problem.img.flow': 'Flujo de operación automatizado',
    'problem.img.mobile': 'Seguimiento móvil de operación',
    'problem.img.tools': 'Herramientas de trabajo conectadas',

    // Section3HowItWorks
    'howitworks.titulo': 'Así de simple funciona',
    'howitworks.sub': 'Tres pilares. Todo conectado. Tu negocio opera solo.',
    'howitworks.step1.label': 'Paso 1',
    'howitworks.step1.titulo': 'Agenda automática',
    'howitworks.step1.desc': 'Tus clientes agendan por WhatsApp. El sistema confirma, envía recordatorios y reagenda si cancelan. Tú no tocas nada.',
    'howitworks.step2.label': 'Paso 2',
    'howitworks.step2.titulo': 'Ventas registradas solas',
    'howitworks.step2.desc': 'Cada cobro se guarda automáticamente. Sabes cuánto vendiste, quién vendió y qué horas son más productivas. Sin calcular nada.',
    'howitworks.step3.label': 'Paso 3',
    'howitworks.step3.titulo': 'Todo visible en tu celular',
    'howitworks.step3.desc': 'Un dashboard te muestra lo que pasa en tu negocio en tiempo real. Desde donde estés. Sin depender de que alguien te reporte.',

    // SectionTimeControl
    'tc.label': 'Reforma laboral 40 hrs',
    'tc.titulo': 'Control de tiempo para',
    'tc.titulo2': 'empleados',
    'tc.desc': 'La nueva reforma de 40 horas laborales exige llevar un registro preciso de la jornada de tus empleados. Nosotros instalamos el sistema en tu negocio —hardware, software y soporte— para que cumplas sin complicaciones.',
    'tc.btn1': 'Ver sistema completo',
    'tc.btn2': 'Consultar por WhatsApp',
    'tc.img': 'Dashboard de control de personal',
    'tc.licencias.titulo': 'Licencias del sistema',
    'tc.licencias.sub': 'Elige el plan que mejor se adapte a tu negocio. Todos incluyen el software, actualizaciones y soporte básico.',
    'tc.plan1.nombre': 'Mensual',
    'tc.plan1.sub': '/mes',
    'tc.plan1.desc': 'Pago recurrente mensual. Ideal para empezar sin compromiso.',
    'tc.plan2.nombre': 'Trimestral',
    'tc.plan2.sub': '/trimestre',
    'tc.plan2.desc': 'Ahorra ~13% vs. mensual. Facturación cada 3 meses.',
    'tc.plan3.nombre': 'Semestral',
    'tc.plan3.sub': '/semestre',
    'tc.plan3.desc': 'Ahorra ~26% vs. mensual. Facturación cada 6 meses.',
    'tc.plan4.nombre': 'Anual',
    'tc.plan4.sub': '/año',
    'tc.plan4.desc': 'Ahorra ~41% vs. mensual. Un solo pago, sin preocupaciones.',
    'tc.especiales': 'Proyectos especiales se cotizan por separado —',
    'tc.especiales.link': 'solicitar cotización',
    'tc.self.title': 'Self-hosted · tú pones la infraestructura',
    'tc.self.desc': 'Si prefieres que el sistema corra en tu propio servidor, puedes llevar el mantenimiento tú mismo. Sin cuotas de licencia recurrentes — solo el costo anual estimado de tu VPS, equipo y servicios de IA (~',
    'tc.self.tax': 'Deducible de impuestos — revisa con tu contador.',

    // SectionSurveyDemo
    'sd.label': 'CX Intelligence',
    'sd.titulo1': 'La información que se te escapa,',
    'sd.titulo2': 'ahora trabaja para ti.',
    'sd.sub': 'Cada cliente que se va sin decir nada es información perdida. El sistema captura esa retroalimentación, la estructura y la manda al webhook para generar reportes y alertas accionables.',
    'sd.problema.label': 'El problema',
    'sd.problema.titulo': '¿Qué pasa con el feedback que no se recoge?',
    'sd.problema.desc': 'El 90% de los clientes insatisfechos simplemente se van sin decir nada. Sin datos, no hay mejora. Sin retroalimentación, repites los mismos errores.',
    'sd.solucion.label': 'La solución',
    'sd.solucion.titulo': 'Agentes de IA que capturan lo que se pierde',
    'sd.ai1.titulo': 'Sentiment Analysis',
    'sd.ai1.desc': 'Clasifica cada respuesta como positiva, neutral o negativa automáticamente.',
    'sd.ai2.titulo': 'Tagging Inteligente',
    'sd.ai2.desc': 'Extrae temas clave: calidad, tiempo, precio, servicio, personal.',
    'sd.ai3.titulo': 'Detección de Patrones',
    'sd.ai3.desc': 'Identifica tendencias: "los viernes hay más quejas", "el servicio X es el mejor calificado".',
    'sd.ai4.titulo': 'Alertas en Tiempo Real',
    'sd.ai4.desc': 'Si algo va mal, lo sabes al instante. Sin esperar a revisar encuestas manualmente.',
    'sd.flow.label': 'El flujo de datos',
    'sd.flow1': 'QR / Link',
    'sd.flow1.desc': 'El cliente escanea o recibe un link por WhatsApp',
    'sd.flow2': 'Encuesta 30s',
    'sd.flow2.desc': 'Responde 3-4 preguntas simples, sin fricción',
    'sd.flow3': 'IA Procesa',
    'sd.flow3.desc': 'Analiza sentimiento, detecta tags, identifica patrones',
    'sd.flow4': 'Data Estructurada',
    'sd.flow4.desc': 'Cada respuesta se convierte en datos accionables',
    'sd.flow5': 'Reporte / Alerta',
    'sd.flow5.desc': 'Dashboard diario + alertas inmediatas para decidir',
    'sd.demo.intro': 'Prueba el sistema',
    'sd.demo.intro.desc': 'Tómate 30 segundos para responder como lo haría tu cliente. La IA analiza todo al instante.',
    'sd.demo.btn': 'Iniciar demo',
    'sd.demo.analyzing': 'Preparando reporte',
    'sd.demo.alert.label': 'Alerta inmediata',
    'sd.demo.alert.title': 'Cliente insatisfecho detectado',
    'sd.demo.alert.info': 'Así lo recibe el dueño',
    'sd.demo.alert.sub': 'En su celular, al instante. Sin abrir plataformas.',
    'sd.demo.alert.btn': 'Ver reporte completo',
    'sd.demo.report.card': 'soul:23 Feedback Report',
    'sd.demo.report.sub': 'Reporte de ejemplo generado con respuestas simuladas',
    'sd.demo.report.title': 'Resumen del análisis',
    'sd.demo.report.priority': 'Prioridad',
    'sd.demo.report.responses': 'Respuestas',
    'sd.demo.report.alerts': 'Alertas',
    'sd.demo.report.tags': 'Tags detectados',
    'sd.demo.report.sentiment': 'Sentimiento general',
    'sd.demo.report.topic': 'Top tema',
    'sd.demo.report.footer': 'Powered by soul:23 · Feedback automatizado con IA',
    'sd.demo.report.btn': 'Probar otra vez',
    'sd.stats1.val': '90%',
    'sd.stats1.label': 'de feedback se pierde sin este sistema',
    'sd.stats2.val': '30s',
    'sd.stats2.label': 'tiempo promedio de una encuesta',
    'sd.stats3.val': '24/7',
    'sd.stats3.label': 'captura de datos automatizada',
    'sd.cta': 'Quiero este sistema para mi negocio',
    'sd.cta.sub': 'Compatible con cualquier giro: restaurantes, spas, clínicas, tiendas, escuelas',

    // Section4Projects
    'proyectos.titulo': 'Negocios que ya operan solos',
    'proyectos.sub': 'Historias reales de negocios como el tuyo.',

    // Section5Testimonials
    'testimonios.titulo': 'Lo que dicen quienes ya lo viven',

    // Section9Contact
    'contacto.titulo': 'Platicanos de tu caso',
    'contacto.sub': 'Responde el mini diagnóstico. El webhook recibe todo con tipo de formulario y datos listos para generar reporte.',
    'contacto.habla': 'Habla con nosotros',

    // Footer
    'footer.tagline': 'Sistemas para que tu negocio trabaje solo.',
    'footer.servicios': 'Servicios',
    'footer.planes': 'Planes',
    'footer.privacidad': 'Privacidad',
    'footer.reembolso': 'Reembolso',
    'footer.terminos': 'Términos',
    'footer.copyright': '© 2026 · soul:23',

    // Projects status
    'proyectos.status.adjusting': 'en ajuste',

    // Testimonials
    'testimonios.0.text': 'Necesitaba que mi página de verdad transmitiera lo que hago, porque antes se sentía todo muy frío. Ahora mis pacientes entran, ven de qué trata la terapia y agendan su cita sin que yo tenga que estar enviando mensajes de ida y vuelta. Se siente todo mucho más profesional y organizado, pero sobre todo me quitó un peso de encima con la administración.',
    'testimonios.0.name': 'Gloria',
    'testimonios.0.business': 'Terapeuta',
    'testimonios.1.text': 'La verdad es que antes me volvía loca con los cuadernos y las agendas de papel; entre las tres sucursales era un relajo. Lo que más me cambió la vida fue dejar de hacer los pagos de las muchachas a mano y no tener que estar cazando las ventas del día. Ahora todo se calcula solo y por fin sé qué onda con los tiempos muertos sin estar pegada ahí.',
    'testimonios.1.name': 'Alejandra',
    'testimonios.1.business': 'Salón de belleza',
    'testimonios.2.text': 'Yo lo que quería era dejar de perder el tiempo revisando plataformas de encuestas que ni entendía. Ahora las reservas caen solas y lo que dicen los clientes me llega directo al celular. Mi gente y yo ya no tenemos que andar adivinando; tenemos la info ahí mismo al momento. Me ahorré muchísimas vueltas y el sistema se encarga de todo.',
    'testimonios.2.name': 'Roberto Pérez',
    'testimonios.2.business': 'Restaurante',

    // Contact form config
    'contacto.config.name': 'Mini diagnóstico de encuestas',
    'contacto.config.welcome.headline': 'Cuéntanos qué quieres medir',
    'contacto.config.welcome.subheader': 'Con tus respuestas armamos un primer reporte para tu correo y vemos si conviene una llamada.',
    'contacto.config.welcome.buttonLabel': 'Empezar',
    'contacto.q.tipo_negocio.headline': 'Primero: ¿en qué giro está tu negocio?',
    'contacto.q.tipo_negocio.subheader': 'Esto cambia el lenguaje, métricas y preguntas que conviene usar.',
    'contacto.q.tipo_encuesta.headline': 'Ahora elige qué tipo de encuesta quieres hacer',
    'contacto.q.tipo_encuesta.subheader': 'Puedes elegir más de una. Esto se manda al webhook como selección completa para generar emails y reporte.',
    'contacto.q.nombre.headline': '¿Cómo te llamas?',
    'contacto.q.nombre.placeholder': 'Tu nombre',
    'contacto.q.negocio.headline': '¿Cómo se llama tu negocio?',
    'contacto.q.negocio.placeholder': 'Nombre del negocio',
    'contacto.q.email.headline': '¿A qué correo enviamos el reporte?',
    'contacto.q.email.placeholder': 'correo@ejemplo.com',
    'contacto.q.email.validation': 'Correo electrónico inválido.',
    'contacto.q.telefono.headline': '¿Tu WhatsApp?',
    'contacto.q.telefono.placeholder': '8441234567',
    'contacto.q.telefono.validation': 'Debe tener entre 10 y 13 dígitos.',
    'contacto.q.canal.headline': '¿Dónde quieres levantar respuestas?',
    'contacto.q.audiencia.headline': '¿Quién va a responder esa encuesta?',
    'contacto.q.audiencia.subheader': 'Esto ayuda a que el correo no suene genérico y use el contexto correcto.',
    'contacto.q.momento.headline': '¿En qué momento quieres pedir la respuesta?',
    'contacto.q.momento.subheader': 'El momento define automatizaciones, recordatorios y alertas.',
    'contacto.q.necesidad.headline': '¿Qué debería pasar después de responder?',
    'contacto.q.urgencia.headline': '¿Cuándo te gustaría tenerlo funcionando?',
    'contacto.q.decision.headline': '¿Qué decisión quieres poder tomar con esas respuestas?',
    'contacto.q.decision.subheader': 'Ejemplo: saber por qué cancelan, qué curso vender más, qué empleado necesita apoyo.',
    'contacto.q.decision.placeholder': 'Quiero decidir...',
    'contacto.q.pregunta_clave.headline': '¿Cuál es la pregunta que no te puedes quitar de la cabeza?',
    'contacto.q.pregunta_clave.subheader': 'La usaremos como centro del reporte que recibe el cliente.',
    'contacto.q.pregunta_clave.placeholder': 'Necesito saber si...',
    'contacto.q.alerta_critica.headline': '¿Qué respuesta debería prender una alerta inmediata?',
    'contacto.q.alerta_critica.subheader': 'Ejemplo: mala atención, cancelación, queja grave, empleado saturado, lead urgente.',
    'contacto.q.alerta_critica.placeholder': 'Alertar si alguien responde...',
    'contacto.q.descripcion.headline': '¿Algo más que deba saber Talia para personalizar el reporte?',
    'contacto.q.descripcion.subheader': 'Contexto operativo, sucursales, volumen, problema actual o cómo hoy levantan feedback.',
    'contacto.q.descripcion.placeholder': 'Hoy lo hacemos así...',
    'contacto.ending.headline': 'Recibimos tu diagnóstico',
    'contacto.ending.subheader': 'El webhook generará el reporte y lo enviará al correo capturado cuando esté configurado.',
    'contacto.email.label': 'Email',
    'contacto.email.cta': 'Escribir →',
    'contacto.whatsapp.label': 'WhatsApp',
    'contacto.whatsapp.cta': 'Abrir chat →',
    'contacto.talia.label': 'Talia · citas',
    'contacto.talia.cta': 'Escribir →',
    'contacto.agendar': 'Agendar llamada',
    'contacto.closed.title': 'Diagnóstico cerrado',
    'contacto.closed.desc': 'Puedes volver a abrirlo cuando quieras para elegir giro, tipo de encuesta y automatizaciones.',
    'contacto.closed.btn': 'Abrir diagnóstico',

    // SD Demo keys
    'sd.demo.survey.excellent': 'Excelente',
    'sd.demo.survey.regular': 'Regular',
    'sd.demo.survey.bad': 'Mala',
    'sd.demo.survey.question': 'Pregunta',
    'sd.demo.survey.of': 'de',
    'sd.demo.feature.1': 'Sin formularios largos',
    'sd.demo.feature.2': 'Alertas en tiempo real',
    'sd.demo.feature.3': 'Reporte diario automático',
    'sd.demo.feature.4': 'Detección de patrones IA',
    'sd.demo.alert.now': 'Ahora',
    'sd.demo.alert.msg.negative': 'Experiencia negativa reportada',
    'sd.demo.alert.msg.positive': 'Cliente satisfecho',
    'sd.demo.alert.msg.neutral': 'Retroalimentación recibida',
    'sd.demo.report.focus': 'Reporte enfocado en',
    'sd.demo.report.seeks': 'El reporte busca',
    'sd.demo.report.case': 'Caso:',
    'sd.demo.report.analysis.negative': 'Se detectaron señales de insatisfacción. Revisar tema operativo.',
    'sd.demo.report.analysis.positive': 'Retroalimentación positiva. Identificar qué funcionó bien.',
    'sd.demo.report.analysis.neutral': 'Sin alertas críticas. Seguir monitoreando tendencias.',
    'sd.demo.sentiment.positive': 'Positivo',
    'sd.demo.sentiment.negative': 'Negativo',
    'sd.demo.sentiment.neutral': 'Neutral',
    'sd.demo.report.priority.high': 'Alta',
    'sd.demo.report.priority.medium': 'Media',
    'sd.demo.report.priority.low': 'Baja',
    'sd.typing.1': 'Clasificando sentimiento...',
    'sd.typing.2': 'Extrayendo tags: experiencia, tiempo, calidad...',
    'sd.typing.3': 'Detectando patrón...',
    'sd.typing.4': 'Generando alerta por respuesta negativa...',
    'sd.typing.5': 'Compilando reporte...',
    'sd.liveform.section.label': 'Formularios reales',
    'sd.liveform.section.title': 'Elige qué flujo quieres probar.',
    'sd.liveform.section.desc': 'Estos sí son los formularios que mandan al webhook con su type, reporte y plantillas de correo para Talia.',
    'sd.liveform.window.title': 'Ventana de prueba',
    'sd.liveform.window.desc': 'Elige un flujo de abajo y se abrirá aquí mismo, sin mandarte a otra sección ni sacar al usuario del contexto.',
    'sd.liveform.close': 'Cerrar formulario',
    'sd.liveform.diagnostico.label': 'Diagnóstico',
    'sd.liveform.diagnostico.title': 'Quiero crear una encuesta para mi negocio',
    'sd.liveform.diagnostico.desc': 'Pregunta giro, tipo de encuesta, canales y automatizaciones.',
    'sd.liveform.clientes.label': 'Clientes',
    'sd.liveform.clientes.title': 'Encuesta post-servicio',
    'sd.liveform.clientes.desc': 'Para QR, WhatsApp o link después de una compra/cita.',
    'sd.liveform.proyecto.label': 'Proyecto',
    'sd.liveform.proyecto.title': 'Onboarding de cliente',
    'sd.liveform.proyecto.desc': 'Para levantar contexto antes de construir un sistema.',
    'sd.liveform.eventos.label': 'Eventos',
    'sd.liveform.eventos.title': 'RSVP / confirmación',
    'sd.liveform.eventos.desc': 'Para asistencia, invitados, preferencias y seguimiento.',
    'sd.liveform.staff.label': 'Staff',
    'sd.liveform.staff.title': 'Evaluación de personal',
    'sd.liveform.staff.desc': 'Para desempeño, clima, bloqueos y capacitación.',
    'sd.liveform.cierre.label': 'Cierre',
    'sd.liveform.cierre.title': 'Feedback post-proyecto',
    'sd.liveform.cierre.desc': 'Para NPS, entrega, comunicación y segunda fase.',

    // ServicesPage
    'services.back': 'Volver',
    'services.title': 'Servicios individuales',
    'services.subtitle': 'Cada servicio puede contratarse de forma independiente o formar parte de un plan mensual. Todos los sistemas se diseñan a la medida de tu operación.',
    'services.discountNote': '* Promo lanzamiento · No acumulable con otras promociones (ej. newsletter)',
    'services.cta.question': '¿No encuentras lo que buscas? Todo sistema se adapta a tu negocio.',
    'services.cta.plans': 'Ver planes',
    'services.cta.whatsapp': 'Consultar por WhatsApp',

    // SurveyEngine
    'survey.welcome.badge': 'soul:23 Experience',
    'survey.required': 'Requerido',
    'survey.back': 'Atrás',
    'survey.next': 'Siguiente',
    'survey.submit': 'Enviar',
    'survey.close': 'Cerrar',
    'survey.progress': 'Progreso',
    'survey.restart': 'Reiniciar encuesta',
    'survey.error.required': 'Esta respuesta es obligatoria.',

    // Competency Evaluation
    'competencias.back': 'Volver',
    'competencias.label': 'Evaluación Técnica',
    'competencias.titulo': 'Evaluación de competencias que se adapta a tu industria',
    'competencias.subtitulo': 'Sistema de evaluación técnica con routing inteligente, calificación automática y reportes por categoría. Desde operadores hasta ingenieros. Desde manufactura hasta tecnología.',
    'competencias.cta1': 'Cotizar mi evaluación',
    'competencias.cta2': 'Consultar por WhatsApp',
    'competencias.industrias.titulo': 'Para cualquier industria',
    'competencias.industrias.sub': 'El sistema se adapta a las competencias técnicas de tu sector, no al revés.',
    'competencias.niveles.titulo': 'Niveles adaptativos',
    'competencias.niveles.sub': 'Tres niveles de dificultad que se asignan automáticamente según el rol y experiencia del evaluado.',
    'competencias.flujo.titulo': 'Cómo funciona',
    'competencias.flujo.sub': 'De la registración al reporte ejecutivo en 4 pasos automatizados.',
    'competencias.features.titulo': 'Características del sistema',
    'competencias.features.sub': 'Todo lo que necesitas para evaluar, diagnosticar y desarrollar talento técnico.',
    'competencias.reporte.titulo': 'Reporte ejecutivo',
    'competencias.reporte.sub': 'Cada evaluación genera un PDF con puntuación global, análisis por categoría y plan de desarrollo.',
    'competencias.integracion.titulo': 'Se integra con tu operación',
    'competencias.integracion.sub': 'Conectamos el sistema a tu CRM, ERP o flujo de n8n para que los resultados fluyan directo a donde los necesitas.',
    'competencias.integracion.cta1': 'Quiero una demo',
    'competencias.integracion.cta2': 'Hablar por WhatsApp',

    'competenciasHighlight.label': 'Nuevo sistema',
    'competenciasHighlight.titulo': 'Evaluación de competencias con IA para cualquier industria',
    'competenciasHighlight.sub': 'Sistema de evaluación técnica con routing inteligente que asigna el nivel correcto según rol y experiencia. Calificación automática, reporte PDF ejecutivo y diagnóstico por categoría.',
    'competenciasHighlight.cta1': 'Ver el sistema',
    'competenciasHighlight.cta2': 'Consultar por WhatsApp',
    'competenciasHighlight.stat1': 'Niveles adaptativos',
    'competenciasHighlight.stat2': 'Categorías evaluadas',
    'competenciasHighlight.stat3': 'Industrias soportadas',
    'competenciasHighlight.stat4Val': 'Auto',
    'competenciasHighlight.stat4': 'Calificación automática',
    'competenciasHighlight.preview.titulo': 'Así se ve un reporte',
    'competenciasHighlight.preview.sub': 'Ejemplo de salida del sistema de evaluación',
    'competenciasHighlight.preview.score': 'Puntuación global',
    'competenciasHighlight.preview.cats': 'Categorías aprobadas',
    'competenciasHighlight.preview.level': 'Nivel Medio',
    'competenciasHighlight.preview.levelLabel': 'Competencia asignada',
    'competenciasHighlight.preview.cat1': 'Procesos técnicos',
    'competenciasHighlight.preview.cat2': 'Seguridad industrial',
    'competenciasHighlight.preview.cat3': 'Resolución de problemas',
  },

  EN: {
    'nav.como-funciona': 'How it works',
    'nav.servicios': 'Services',
    'nav.demos': 'Demos',
    'nav.proyectos': 'Projects',
    'nav.precios': 'Pricing',
    'nav.contacto': 'Contact',
    'nav.inicio': 'Home',
    'nav.agendar': 'Book a call',
    'nav.competencias': 'Competencies',
    'theme.dark': 'Dark',
    'theme.light': 'Light',

    'hero.titulo1': 'Your business can',
    'hero.titulo2': 'work on its own.',
    'hero.sub': 'We connect your appointments, sales and operations in one system. You stop doing everything by hand. Your business starts to flow.',
    'hero.btn1': 'See how it works',
    'hero.btn2': 'Talk on WhatsApp',
    'hero.floating': 'vanity academy · dashboard · ia survey',
    'hero.img.soul23': 'soul:23',
    'hero.img.cursos': 'Vanity Academy Courses',
    'hero.img.dashboard': 'Operations Dashboard',
    'hero.img.sitio': 'Dra. DFG Website',
    'hero.img.reporte': 'AI Survey Report',

    'problem.titulo': 'Does this sound familiar…',
    'problem.sub': "You're not alone. Most businesses in Mexico run like this:",
    'problem.1': "You spend all day replying to messages to book appointments",
    'problem.2': 'You do the math by hand to know how much you sold',
    'problem.3': "You don't know what happens in your business when you're not there",
    'problem.4': 'Your employees show up late and nothing gets recorded',
    'problem.5': 'Clients cancel and you have no control',
    'problem.cta': "That can change. And it's not as complicated as you think.",
    'problem.img.flow': 'Automated operations flow',
    'problem.img.mobile': 'Mobile operations tracking',
    'problem.img.tools': 'Connected work tools',

    'howitworks.titulo': 'That\'s how simple it works',
    'howitworks.sub': 'Three pillars. All connected. Your business runs itself.',
    'howitworks.step1.label': 'Step 1',
    'howitworks.step1.titulo': 'Auto Scheduling',
    'howitworks.step1.desc': 'Your clients book via WhatsApp. The system confirms, sends reminders and reschedules if they cancel. You don\'t touch a thing.',
    'howitworks.step2.label': 'Step 2',
    'howitworks.step2.titulo': 'Sales tracked automatically',
    'howitworks.step2.desc': 'Every payment is saved automatically. You know how much you sold, who sold it and which hours are most productive. No calculations needed.',
    'howitworks.step3.label': 'Step 3',
    'howitworks.step3.titulo': 'Everything visible on your phone',
    'howitworks.step3.desc': 'A dashboard shows what\'s happening in your business in real time. From anywhere. Without depending on someone reporting to you.',

    'tc.label': '40hr Labor Reform',
    'tc.titulo': 'Time control for',
    'tc.titulo2': 'employees',
    'tc.desc': 'The new 40-hour workweek reform requires accurate tracking of your employees\' hours. We install the system in your business — hardware, software and support — so you comply without complications.',
    'tc.btn1': 'View full system',
    'tc.btn2': 'Ask on WhatsApp',
    'tc.img': 'Employee time control dashboard',
    'tc.licencias.titulo': 'System Licenses',
    'tc.licencias.sub': 'Choose the plan that best fits your business. All include software, updates and basic support.',
    'tc.plan1.nombre': 'Monthly',
    'tc.plan1.sub': '/mo',
    'tc.plan1.desc': 'Monthly recurring payment. Ideal to start without commitment.',
    'tc.plan2.nombre': 'Quarterly',
    'tc.plan2.sub': '/quarter',
    'tc.plan2.desc': 'Save ~13% vs. monthly. Billed every 3 months.',
    'tc.plan3.nombre': 'Semi-annual',
    'tc.plan3.sub': '/6mo',
    'tc.plan3.desc': 'Save ~26% vs. monthly. Billed every 6 months.',
    'tc.plan4.nombre': 'Annual',
    'tc.plan4.sub': '/year',
    'tc.plan4.desc': 'Save ~41% vs. monthly. Single payment, worry-free.',
    'tc.especiales': 'Special projects are quoted separately —',
    'tc.especiales.link': 'request a quote',
    'tc.self.title': 'Self-hosted · you provide the infrastructure',
    'tc.self.desc': 'If you prefer the system to run on your own server, you handle the maintenance. No recurring license fees — just the estimated annual cost of your VPS, equipment and AI services (~',
    'tc.self.tax': 'Tax deductible — check with your accountant.',

    'sd.label': 'CX Intelligence',
    'sd.titulo1': 'The information that slips away,',
    'sd.titulo2': 'now works for you.',
    'sd.sub': 'Every customer who leaves without saying a word is lost information. The system captures that feedback, structures it and sends it to the webhook to generate reports and actionable alerts.',
    'sd.problema.label': 'The problem',
    'sd.problema.titulo': 'What happens to feedback that isn\'t collected?',
    'sd.problema.desc': '90% of unsatisfied customers simply leave without saying anything. Without data, there\'s no improvement. Without feedback, you repeat the same mistakes.',
    'sd.solucion.label': 'The solution',
    'sd.solucion.titulo': 'AI agents that capture what\'s lost',
    'sd.ai1.titulo': 'Sentiment Analysis',
    'sd.ai1.desc': 'Automatically classifies each response as positive, neutral or negative.',
    'sd.ai2.titulo': 'Smart Tagging',
    'sd.ai2.desc': 'Extracts key themes: quality, time, price, service, staff.',
    'sd.ai3.titulo': 'Pattern Detection',
    'sd.ai3.desc': 'Identifies trends: "Fridays have more complaints", "Service X is the highest rated".',
    'sd.ai4.titulo': 'Real-Time Alerts',
    'sd.ai4.desc': 'If something goes wrong, you know instantly. No need to manually review surveys.',
    'sd.flow.label': 'Data flow',
    'sd.flow1': 'QR / Link',
    'sd.flow1.desc': 'Customer scans or receives a WhatsApp link',
    'sd.flow2': '30s Survey',
    'sd.flow2.desc': 'Answers 3-4 simple questions, no friction',
    'sd.flow3': 'AI Processes',
    'sd.flow3.desc': 'Analyzes sentiment, detects tags, identifies patterns',
    'sd.flow4': 'Structured Data',
    'sd.flow4.desc': 'Every answer becomes actionable data',
    'sd.flow5': 'Report / Alert',
    'sd.flow5.desc': 'Daily dashboard + instant alerts for decisions',
    'sd.demo.intro': 'Try the system',
    'sd.demo.intro.desc': 'Take 30 seconds to answer like your customer would. AI analyzes everything instantly.',
    'sd.demo.btn': 'Start demo',
    'sd.demo.analyzing': 'Preparing report',
    'sd.demo.alert.label': 'Instant alert',
    'sd.demo.alert.title': 'Unsatisfied customer detected',
    'sd.demo.alert.info': 'This is how the owner receives it',
    'sd.demo.alert.sub': 'On their phone, instantly. No need to open platforms.',
    'sd.demo.alert.btn': 'View full report',
    'sd.demo.report.card': 'soul:23 Feedback Report',
    'sd.demo.report.sub': 'Sample report generated with simulated responses',
    'sd.demo.report.title': 'Analysis summary',
    'sd.demo.report.priority': 'Priority',
    'sd.demo.report.responses': 'Responses',
    'sd.demo.report.alerts': 'Alerts',
    'sd.demo.report.tags': 'Detected tags',
    'sd.demo.report.sentiment': 'Overall sentiment',
    'sd.demo.report.topic': 'Top topic',
    'sd.demo.report.footer': 'Powered by soul:23 · Automated feedback with AI',
    'sd.demo.report.btn': 'Try again',
    'sd.stats1.val': '90%',
    'sd.stats1.label': 'of feedback is lost without this system',
    'sd.stats2.val': '30s',
    'sd.stats2.label': 'average survey time',
    'sd.stats3.val': '24/7',
    'sd.stats3.label': 'automated data capture',
    'sd.cta': 'I want this system for my business',
    'sd.cta.sub': 'Compatible with any industry: restaurants, spas, clinics, shops, schools',

    'proyectos.titulo': 'Businesses that already run themselves',
    'proyectos.sub': 'Real stories from businesses like yours.',

    'testimonios.titulo': 'What people are saying',

    'contacto.titulo': 'Tell us about your case',
    'contacto.sub': 'Answer the mini diagnostic. The webhook receives everything with form type and ready-to-use data.',
    'contacto.habla': 'Talk to us',

    'footer.tagline': 'Systems for your business to work on its own.',
    'footer.servicios': 'Services',
    'footer.planes': 'Pricing',
    'footer.privacidad': 'Privacy',
    'footer.reembolso': 'Refunds',
    'footer.terminos': 'Terms',
    'footer.copyright': '© 2026 · soul:23',

    'proyectos.status.adjusting': 'in review',

    'testimonios.0.text': 'I needed my page to truly convey what I do, because before everything felt very cold. Now my patients come in, see what therapy is about and book their appointment without me having to send back-and-forth messages. Everything feels much more professional and organized, but above all it took a weight off my shoulders with administration.',
    'testimonios.0.name': 'Gloria',
    'testimonios.0.business': 'Therapist',
    'testimonios.1.text': 'Honestly, before I was going crazy with notebooks and paper agendas; between three branches it was a mess. What changed my life the most was stopping doing the girls\' payroll by hand and not having to chase daily sales. Now everything calculates itself and I finally know what\'s up with dead times without being glued there.',
    'testimonios.1.name': 'Alejandra',
    'testimonios.1.business': 'Beauty salon',
    'testimonios.2.text': 'What I wanted was to stop wasting time reviewing survey platforms I didn\'t even understand. Now reservations come in on their own and what customers say reaches my phone directly. My team and I no longer have to guess; we have the info right there at the moment. I saved myself so much back-and-forth and the system handles everything.',
    'testimonios.2.name': 'Roberto Pérez',
    'testimonios.2.business': 'Restaurant',

    'contacto.config.name': 'Mini diagnostic survey',
    'contacto.config.welcome.headline': 'Tell us what you want to measure',
    'contacto.config.welcome.subheader': 'With your answers we build a first report for your email and see if a call makes sense.',
    'contacto.config.welcome.buttonLabel': 'Start',
    'contacto.q.tipo_negocio.headline': 'First: what industry is your business in?',
    'contacto.q.tipo_negocio.subheader': 'This changes the language, metrics and questions that make sense to use.',
    'contacto.q.tipo_encuesta.headline': 'Now choose what type of survey you want to run',
    'contacto.q.tipo_encuesta.subheader': 'You can choose more than one. This sends to the webhook as a complete selection to generate emails and report.',
    'contacto.q.nombre.headline': 'What\'s your name?',
    'contacto.q.nombre.placeholder': 'Your name',
    'contacto.q.negocio.headline': 'What\'s your business called?',
    'contacto.q.negocio.placeholder': 'Business name',
    'contacto.q.email.headline': 'What email should we send the report to?',
    'contacto.q.email.placeholder': 'email@example.com',
    'contacto.q.email.validation': 'Invalid email address.',
    'contacto.q.telefono.headline': 'Your WhatsApp?',
    'contacto.q.telefono.placeholder': '8441234567',
    'contacto.q.telefono.validation': 'Must be between 10 and 13 digits.',
    'contacto.q.canal.headline': 'Where do you want to collect responses?',
    'contacto.q.audiencia.headline': 'Who will answer that survey?',
    'contacto.q.audiencia.subheader': 'This helps the email not sound generic and use the right context.',
    'contacto.q.momento.headline': 'When do you want to ask for the response?',
    'contacto.q.momento.subheader': 'The moment defines automations, reminders and alerts.',
    'contacto.q.necesidad.headline': 'What should happen after responding?',
    'contacto.q.urgencia.headline': 'When would you like it working?',
    'contacto.q.decision.headline': 'What decision do you want to make with those responses?',
    'contacto.q.decision.subheader': 'Example: know why they cancel, what course to sell more, which employee needs support.',
    'contacto.q.decision.placeholder': 'I want to decide...',
    'contacto.q.pregunta_clave.headline': 'What\'s the question you can\'t get out of your head?',
    'contacto.q.pregunta_clave.subheader': 'We\'ll use it as the center of the report the client receives.',
    'contacto.q.pregunta_clave.placeholder': 'I need to know if...',
    'contacto.q.alerta_critica.headline': 'What response should trigger an immediate alert?',
    'contacto.q.alerta_critica.subheader': 'Example: bad service, cancellation, serious complaint, overloaded employee, urgent lead.',
    'contacto.q.alerta_critica.placeholder': 'Alert if someone answers...',
    'contacto.q.descripcion.headline': 'Anything else Talia should know to personalize the report?',
    'contacto.q.descripcion.subheader': 'Operational context, branches, volume, current problem or how you currently collect feedback.',
    'contacto.q.descripcion.placeholder': 'Today we do it like this...',
    'contacto.ending.headline': 'We received your diagnostic',
    'contacto.ending.subheader': 'The webhook will generate the report and send it to the captured email when configured.',
    'contacto.email.label': 'Email',
    'contacto.email.cta': 'Write →',
    'contacto.whatsapp.label': 'WhatsApp',
    'contacto.whatsapp.cta': 'Open chat →',
    'contacto.talia.label': 'Talia · appointments',
    'contacto.talia.cta': 'Write →',
    'contacto.agendar': 'Schedule call',
    'contacto.closed.title': 'Diagnostic closed',
    'contacto.closed.desc': 'You can reopen it anytime to choose industry, survey type and automations.',
    'contacto.closed.btn': 'Open diagnostic',

    'sd.demo.survey.excellent': 'Excellent',
    'sd.demo.survey.regular': 'Regular',
    'sd.demo.survey.bad': 'Bad',
    'sd.demo.survey.question': 'Question',
    'sd.demo.survey.of': 'of',
    'sd.demo.feature.1': 'No long forms',
    'sd.demo.feature.2': 'Real-time alerts',
    'sd.demo.feature.3': 'Automatic daily report',
    'sd.demo.feature.4': 'AI pattern detection',
    'sd.demo.alert.now': 'Now',
    'sd.demo.alert.msg.negative': 'Negative experience reported',
    'sd.demo.alert.msg.positive': 'Satisfied customer',
    'sd.demo.alert.msg.neutral': 'Feedback received',
    'sd.demo.report.focus': 'Report focused on',
    'sd.demo.report.seeks': 'The report seeks',
    'sd.demo.report.case': 'Case:',
    'sd.demo.report.analysis.negative': 'Signs of dissatisfaction detected. Review operational topic.',
    'sd.demo.report.analysis.positive': 'Positive feedback. Identify what worked well.',
    'sd.demo.report.analysis.neutral': 'No critical alerts. Keep monitoring trends.',
    'sd.demo.sentiment.positive': 'Positive',
    'sd.demo.sentiment.negative': 'Negative',
    'sd.demo.sentiment.neutral': 'Neutral',
    'sd.demo.report.priority.high': 'High',
    'sd.demo.report.priority.medium': 'Medium',
    'sd.demo.report.priority.low': 'Low',
    'sd.typing.1': 'Classifying sentiment...',
    'sd.typing.2': 'Extracting tags: experience, time, quality...',
    'sd.typing.3': 'Detecting pattern...',
    'sd.typing.4': 'Generating alert for negative response...',
    'sd.typing.5': 'Compiling report...',
    'sd.liveform.section.label': 'Real forms',
    'sd.liveform.section.title': 'Choose which flow you want to try.',
    'sd.liveform.section.desc': 'These are the actual forms that send to the webhook with their type, report and email templates for Talia.',
    'sd.liveform.window.title': 'Test window',
    'sd.liveform.window.desc': 'Choose a flow below and it will open right here, without sending you to another section or taking the user out of context.',
    'sd.liveform.close': 'Close form',
    'sd.liveform.diagnostico.label': 'Diagnostic',
    'sd.liveform.diagnostico.title': 'I want to create a survey for my business',
    'sd.liveform.diagnostico.desc': 'Asks industry, survey type, channels and automations.',
    'sd.liveform.clientes.label': 'Customers',
    'sd.liveform.clientes.title': 'Post-service survey',
    'sd.liveform.clientes.desc': 'For QR, WhatsApp or link after a purchase/appointment.',
    'sd.liveform.proyecto.label': 'Project',
    'sd.liveform.proyecto.title': 'Client onboarding',
    'sd.liveform.proyecto.desc': 'To gather context before building a system.',
    'sd.liveform.eventos.label': 'Events',
    'sd.liveform.eventos.title': 'RSVP / confirmation',
    'sd.liveform.eventos.desc': 'For attendance, guests, preferences and follow-up.',
    'sd.liveform.staff.label': 'Staff',
    'sd.liveform.staff.title': 'Staff evaluation',
    'sd.liveform.staff.desc': 'For performance, climate, blockers and training.',
    'sd.liveform.cierre.label': 'Closure',
    'sd.liveform.cierre.title': 'Post-project feedback',
    'sd.liveform.cierre.desc': 'For NPS, delivery, communication and second phase.',

    'services.back': 'Back',
    'services.title': 'Individual Services',
    'services.subtitle': 'Each service can be hired independently or as part of a monthly plan. All systems are designed to fit your operation.',
    'services.discountNote': '* Launch promo · Not combinable with other promotions (e.g. newsletter)',
    'services.cta.question': "Can't find what you're looking for? Every system adapts to your business.",
    'services.cta.plans': 'View plans',
    'services.cta.whatsapp': 'Ask on WhatsApp',

    // SurveyEngine
    'survey.welcome.badge': 'soul:23 Experience',
    'survey.required': 'Required',
    'survey.back': 'Back',
    'survey.next': 'Next',
    'survey.submit': 'Submit',
    'survey.close': 'Close',
    'survey.progress': 'Progress',
    'survey.restart': 'Restart survey',
    'survey.error.required': 'This response is required.',

    // Competency Evaluation
    'competencias.back': 'Back',
    'competencias.label': 'Technical Assessment',
    'competencias.titulo': 'Competency evaluation that adapts to your industry',
    'competencias.subtitulo': 'Technical assessment system with smart routing, automatic grading and category-based reports. From operators to engineers. From manufacturing to technology.',
    'competencias.cta1': 'Get a quote',
    'competencias.cta2': 'Ask on WhatsApp',
    'competencias.industrias.titulo': 'For any industry',
    'competencias.industrias.sub': 'The system adapts to your sector technical competencies, not the other way around.',
    'competencias.niveles.titulo': 'Adaptive levels',
    'competencias.niveles.sub': 'Three difficulty levels automatically assigned based on role and experience.',
    'competencias.flujo.titulo': 'How it works',
    'competencias.flujo.sub': 'From registration to executive report in 4 automated steps.',
    'competencias.features.titulo': 'System features',
    'competencias.features.sub': 'Everything you need to evaluate, diagnose and develop technical talent.',
    'competencias.reporte.titulo': 'Executive report',
    'competencias.reporte.sub': 'Each assessment generates a PDF with global score, category analysis and development plan.',
    'competencias.integracion.titulo': 'Integrates with your operation',
    'competencias.integracion.sub': 'We connect the system to your CRM, ERP or n8n flow so results go directly where you need them.',
    'competencias.integracion.cta1': 'Request a demo',
    'competencias.integracion.cta2': 'Talk on WhatsApp',

    'competenciasHighlight.label': 'New system',
    'competenciasHighlight.titulo': 'AI-powered competency assessment for any industry',
    'competenciasHighlight.sub': 'Technical assessment system with smart routing that assigns the right level based on role and experience. Automatic grading, executive PDF report and category diagnostics.',
    'competenciasHighlight.cta1': 'See the system',
    'competenciasHighlight.cta2': 'Ask on WhatsApp',
    'competenciasHighlight.stat1': 'Adaptive levels',
    'competenciasHighlight.stat2': 'Categories evaluated',
    'competenciasHighlight.stat3': 'Industries supported',
    'competenciasHighlight.stat4Val': 'Auto',
    'competenciasHighlight.stat4': 'Automatic grading',
    'competenciasHighlight.preview.titulo': 'What a report looks like',
    'competenciasHighlight.preview.sub': 'Example output from the assessment system',
    'competenciasHighlight.preview.score': 'Global score',
    'competenciasHighlight.preview.cats': 'Categories passed',
    'competenciasHighlight.preview.level': 'Medium Level',
    'competenciasHighlight.preview.levelLabel': 'Assigned competency',
    'competenciasHighlight.preview.cat1': 'Technical processes',
    'competenciasHighlight.preview.cat2': 'Industrial safety',
    'competenciasHighlight.preview.cat3': 'Problem solving',
  },

  KO: {
    'nav.como-funciona': '작동 방식',
    'nav.servicios': '서비스',
    'nav.demos': '데모',
    'nav.proyectos': '프로젝트',
    'nav.precios': '가격',
    'nav.contacto': '문의',
    'nav.inicio': '홈',
    'nav.agendar': '상담 예약',
    'nav.competencias': '역량 평가',
    'theme.dark': '다크',
    'theme.light': '라이트',

    'hero.titulo1': '귀하의 비즈니스는',
    'hero.titulo2': '스스로 작동할 수 있습니다.',
    'hero.sub': '저희가 예약, 판매, 운영을 하나의 시스템으로 연결합니다. 수동 작업에서 벗어나 비즈니스가 저절로 흘러가게 하세요.',
    'hero.btn1': '작동 방식 보기',
    'hero.btn2': 'WhatsApp 문의',
    'hero.floating': 'vanity academy · dashboard · ia survey',
    'hero.img.soul23': 'soul:23',
    'hero.img.cursos': 'Vanity Academy 코스',
    'hero.img.dashboard': '운영 대시보드',
    'hero.img.sitio': 'Dra. DFG 웹사이트',
    'hero.img.reporte': 'AI 설문 리포트',

    'problem.titulo': '이런 경험이 있으신가요…',
    'problem.sub': '당신만 그런 게 아닙니다. 멕시코 대부분의 비즈니스가 이렇게 운영됩니다:',
    'problem.1': '하루 종일 예약 메시지에 답장하고 있습니다',
    'problem.2': '판매량을 알기 위해 수동으로 계산합니다',
    'problem.3': '자리가 없을 때 비즈니스 상황을 알 수 없습니다',
    'problem.4': '직원들이 지각해도 기록이 없습니다',
    'problem.5': '고객이 취소해도 통제할 수 없습니다',
    'problem.cta': '바꿀 수 있습니다. 생각보다 어렵지 않습니다.',
    'problem.img.flow': '자동화된 운영 흐름',
    'problem.img.mobile': '모바일 운영 추적',
    'problem.img.tools': '연결된 작업 도구',

    'howitworks.titulo': '이렇게 간단하게 작동합니다',
    'howitworks.sub': '세 가지 기둥. 모두 연결. 비즈니스가 스스로 운영됩니다.',
    'howitworks.step1.label': '1단계',
    'howitworks.step1.titulo': '자동 예약',
    'howitworks.step1.desc': '고객이 WhatsApp으로 예약합니다. 시스템이 확인하고 리마인더를 보내며 취소 시 재예약합니다. 당신은 아무것도 건드릴 필요가 없습니다.',
    'howitworks.step2.label': '2단계',
    'howitworks.step2.titulo': '자동 판매 기록',
    'howitworks.step2.desc': '모든 결제가 자동으로 저장됩니다. 판매량, 판매자, 가장 생산적인 시간대를 알 수 있습니다. 계산이 필요 없습니다.',
    'howitworks.step3.label': '3단계',
    'howitworks.step3.titulo': '휴대폰에서 모든 것 확인',
    'howitworks.step3.desc': '대시보드가 비즈니스 상황을 실시간으로 보여줍니다. 어디서든. 누군가의 보고에 의존하지 않고.',

    'tc.label': '40시간 근로 개혁',
    'tc.titulo': '직원 시간',
    'tc.titulo2': '관리 시스템',
    'tc.desc': '새로운 40시간 근무제 개혁은 직원의 근무 시간을 정확히 기록해야 합니다. 당사가 하드웨어, 소프트웨어 및 지원을 포함한 시스템을 설치하여 복잡함 없이 규정을 준수할 수 있도록 도와드립니다.',
    'tc.btn1': '전체 시스템 보기',
    'tc.btn2': 'WhatsApp 문의',
    'tc.img': '직원 시간 관리 대시보드',
    'tc.licencias.titulo': '시스템 라이선스',
    'tc.licencias.sub': '비즈니스에 가장 적합한 요금제를 선택하세요. 모두 소프트웨어, 업데이트 및 기본 지원이 포함됩니다.',
    'tc.plan1.nombre': '월간',
    'tc.plan1.sub': '/월',
    'tc.plan1.desc': '월간 정기 결제. 부담 없이 시작하기에 이상적입니다.',
    'tc.plan2.nombre': '분기',
    'tc.plan2.sub': '/분기',
    'tc.plan2.desc': '월간 대비 ~13% 절약. 3개월마다 청구.',
    'tc.plan3.nombre': '반기',
    'tc.plan3.sub': '/6개월',
    'tc.plan3.desc': '월간 대비 ~26% 절약. 6개월마다 청구.',
    'tc.plan4.nombre': '연간',
    'tc.plan4.sub': '/년',
    'tc.plan4.desc': '월간 대비 ~41% 절약. 일회성 결제로 걱정 없음.',
    'tc.especiales': '특별 프로젝트는 별도 견적 —',
    'tc.especiales.link': '견적 요청',
    'tc.self.title': '셀프 호스팅 · 인프라는 본인이 제공',
    'tc.self.desc': '시스템을 자체 서버에서 실행하려면 유지 관리를 직접 수행하세요. 반복 라이선스 비용 없음 — VPS, 장비 및 AI 서비스의 연간 예상 비용만 (~',
    'tc.self.tax': '세금 공제 가능 — 회계사와 확인하세요.',

    'sd.label': 'CX 인텔리전스',
    'sd.titulo1': '놓치고 있는 정보가',
    'sd.titulo2': '이제 당신을 위해 일합니다.',
    'sd.sub': '아무 말 없이 떠나는 모든 고객은 잃어버린 정보입니다. 시스템이 피드백을 포착하고 구조화하여 웹훅으로 보내 실행 가능한 보고서와 알림을 생성합니다.',
    'sd.problema.label': '문제',
    'sd.problema.titulo': '수집되지 않는 피드백은 어떻게 될까요?',
    'sd.problema.desc': '불만족 고객의 90%는 아무 말 없이 떠납니다. 데이터 없이 개선은 없습니다. 피드백 없이 같은 실수를 반복합니다.',
    'sd.solucion.label': '해결책',
    'sd.solucion.titulo': '놓치는 것을 포착하는 AI 에이전트',
    'sd.ai1.titulo': '감정 분석',
    'sd.ai1.desc': '각 응답을 긍정, 중립 또는 부정으로 자동 분류합니다.',
    'sd.ai2.titulo': '스마트 태깅',
    'sd.ai2.desc': '핵심 주제 추출: 품질, 시간, 가격, 서비스, 직원.',
    'sd.ai3.titulo': '패턴 감지',
    'sd.ai3.desc': '트렌드 식별: "금요일에 불만이 더 많음", "서비스 X가 가장 높은 평가".',
    'sd.ai4.titulo': '실시간 알림',
    'sd.ai4.desc': '문제가 발생하면 즉시 알 수 있습니다. 설문을 수동으로 검토할 필요가 없습니다.',
    'sd.flow.label': '데이터 흐름',
    'sd.flow1': 'QR / 링크',
    'sd.flow1.desc': '고객이 스캔하거나 WhatsApp 링크 수신',
    'sd.flow2': '30초 설문',
    'sd.flow2.desc': '간단한 3-4개 질문에 답변, 마찰 없음',
    'sd.flow3': 'AI 처리',
    'sd.flow3.desc': '감정 분석, 태그 감지, 패턴 식별',
    'sd.flow4': '구조화된 데이터',
    'sd.flow4.desc': '모든 답변이 실행 가능한 데이터로 전환',
    'sd.flow5': '보고서 / 알림',
    'sd.flow5.desc': '일일 대시보드 + 즉시 알림으로 의사 결정',
    'sd.demo.intro': '시스템 체험',
    'sd.demo.intro.desc': '30초 동안 고객처럼 답변해보세요. AI가 즉시 모든 것을 분석합니다.',
    'sd.demo.btn': '데모 시작',
    'sd.demo.analyzing': '보고서 준비 중',
    'sd.demo.alert.label': '즉시 알림',
    'sd.demo.alert.title': '불만족 고객 감지',
    'sd.demo.alert.info': '소유자가 받는 방식',
    'sd.demo.alert.sub': '휴대폰으로 즉시. 플랫폼을 열 필요 없음.',
    'sd.demo.alert.btn': '전체 보고서 보기',
    'sd.demo.report.card': 'soul:23 피드백 보고서',
    'sd.demo.report.sub': '시뮬레이션된 응답으로 생성된 샘플 보고서',
    'sd.demo.report.title': '분석 요약',
    'sd.demo.report.priority': '우선순위',
    'sd.demo.report.responses': '응답',
    'sd.demo.report.alerts': '알림',
    'sd.demo.report.tags': '감지된 태그',
    'sd.demo.report.sentiment': '전체 감정',
    'sd.demo.report.topic': '상위 주제',
    'sd.demo.report.footer': 'Powered by soul:23 · AI 자동 피드백',
    'sd.demo.report.btn': '다시 시도',
    'sd.stats1.val': '90%',
    'sd.stats1.label': '이 시스템 없이 손실되는 피드백',
    'sd.stats2.val': '30초',
    'sd.stats2.label': '평균 설문 시간',
    'sd.stats3.val': '24/7',
    'sd.stats3.label': '자동화된 데이터 캡처',
    'sd.cta': '내 비즈니스에 이 시스템을 원합니다',
    'sd.cta.sub': '모든 업종 호환: 레스토랑, 스파, 병원, 매장, 학교',

    'proyectos.titulo': '이미 자동 운영되는 비즈니스',
    'proyectos.sub': '여러분과 같은 비즈니스의 실제 사례.',

    'testimonios.titulo': '이미 경험한 사람들의 이야기',

    'contacto.titulo': '사례를 알려주세요',
    'contacto.sub': '미니 진단에 답하세요. 웹훅이 모든 데이터를 양식 유형과 함께 수신합니다.',
    'contacto.habla': '문의하기',

    'footer.tagline': '비즈니스가 스스로 작동하게 하는 시스템.',
    'footer.servicios': '서비스',
    'footer.planes': '가격',
    'footer.privacidad': '개인정보',
    'footer.reembolso': '환불',
    'footer.terminos': '이용약관',
    'footer.copyright': '© 2026 · soul:23',

    'proyectos.status.adjusting': '검토 중',

    'testimonios.0.text': '내 페이지가 정말로 내가 하는 일을 전달해야 했는데, 이전에는 모든 것이 너무 차가웠어요. 이제 환자들이 들어와서 치료가 무엇인지 보고 왔다 갔다 메시지를 보낼 필요 없이 예약을 합니다. 모든 것이 훨씬 더 전문적이고 조직적으로 느껴지지만, 무엇보다도 관리에서 어깨의 짐을 덜어주었습니다.',
    'testimonios.0.name': 'Gloria',
    'testimonios.0.business': '치료사',
    'testimonios.1.text': '솔직히 이전에는 공책과 종이 일정표로 미쳐갔어요. 세 지점 사이에서 엉망이었죠. 내 인생을 가장 많이 바꾼 것은 여직원들 급여를 수동으로 하는 것을 그만두고 하루 매출을 쫓아다닐 필요가 없어진 것입니다. 이제 모든 것이 자동으로 계산되고 마침내 거기에 붙어 있지 않아도 죽은 시간이 무엇인지 알 수 있어요.',
    'testimonios.1.name': 'Alejandra',
    'testimonios.1.business': '미용실',
    'testimonios.2.text': '내가 원했던 것은 이해하지도 못하는 설문 플랫폼을 검토하는 데 시간을 낭비하는 것을 그만두는 것이었습니다. 이제 예약이 저절로 들어오고 고객들이 말하는 것이 내 휴대폰으로 직접 전달됩니다. 내 팀과 나는 더 이상 추측할 필요가 없습니다. 순간에 바로 정보가 있습니다. 많은 번거로움을 절약하고 시스템이 모든 것을 처리합니다.',
    'testimonios.2.name': 'Roberto Pérez',
    'testimonios.2.business': '레스토랑',

    'contacto.config.name': '미니 진단 설문',
    'contacto.config.welcome.headline': '무엇을 측정하고 싶은지 알려주세요',
    'contacto.config.welcome.subheader': '귀하의 답변으로 이메일용 첫 보고서를 작성하고 통화가 의미 있는지 확인합니다.',
    'contacto.config.welcome.buttonLabel': '시작',
    'contacto.q.tipo_negocio.headline': '먼저: 귀하의 비즈니스는 어떤 업종입니까?',
    'contacto.q.tipo_negocio.subheader': '이것은 사용하기에 적합한 언어, 지표 및 질문을 변경합니다.',
    'contacto.q.tipo_encuesta.headline': '이제 실행할 설문 유형을 선택하세요',
    'contacto.q.tipo_encuesta.subheader': '여러 개를 선택할 수 있습니다. 이것은 이메일과 보고서를 생성하기 위한 완전한 선택으로 웹훅에 전송됩니다.',
    'contacto.q.nombre.headline': '이름이 무엇입니까?',
    'contacto.q.nombre.placeholder': '귀하의 이름',
    'contacto.q.negocio.headline': '비즈니스 이름은 무엇입니까?',
    'contacto.q.negocio.placeholder': '비즈니스 이름',
    'contacto.q.email.headline': '보고서를 어떤 이메일로 보내드릴까요?',
    'contacto.q.email.placeholder': 'email@example.com',
    'contacto.q.email.validation': '잘못된 이메일 주소입니다.',
    'contacto.q.telefono.headline': 'WhatsApp 번호는?',
    'contacto.q.telefono.placeholder': '8441234567',
    'contacto.q.telefono.validation': '10자리에서 13자리 사이여야 합니다.',
    'contacto.q.canal.headline': '어디서 응답을 수집하고 싶으십니까?',
    'contacto.q.audiencia.headline': '누가 그 설문에 답할 것입니까?',
    'contacto.q.audiencia.subheader': '이것은 이메일이 일반적으로 들리지 않고 올바른 맥락을 사용하는 데 도움이 됩니다.',
    'contacto.q.momento.headline': '언제 응답을 요청하고 싶으십니까?',
    'contacto.q.momento.subheader': '시점이 자동화, 알림 및 경고를 정의합니다.',
    'contacto.q.necesidad.headline': '응답 후 무엇이 일어나야 합니까?',
    'contacto.q.urgencia.headline': '언제 작동하기를 원하십니까?',
    'contacto.q.decision.headline': '그 응답으로 어떤 결정을 내리고 싶으십니까?',
    'contacto.q.decision.subheader': '예: 취소 이유, 더 많이 팔 수 있는 과정, 지원이 필요한 직원.',
    'contacto.q.decision.placeholder': '결정하고 싶습니다...',
    'contacto.q.pregunta_clave.headline': '머릿속에서 떠나지 않는 질문은 무엇입니까?',
    'contacto.q.pregunta_clave.subheader': '클라이언트가 받는 보고서의 중심으로 사용하겠습니다.',
    'contacto.q.pregunta_clave.placeholder': '알아야 할 것이...',
    'contacto.q.alerta_critica.headline': '어떤 응답이 즉각적인 경고를 트리거해야 합니까?',
    'contacto.q.alerta_critica.subheader': '예: 나쁜 서비스, 취소, 심각한 불만, 과로한 직원, 긴급 리드.',
    'contacto.q.alerta_critica.placeholder': '누군가 답하면 경고...',
    'contacto.q.descripcion.headline': 'Talia가 보고서를 개인화하기 위해 알아야 할 추가 사항이 있습니까?',
    'contacto.q.descripcion.subheader': '운영 맥락, 지점, 규모, 현재 문제 또는 현재 피드백 수집 방법.',
    'contacto.q.descripcion.placeholder': '오늘은 이렇게 합니다...',
    'contacto.ending.headline': '귀하의 진단을 받았습니다',
    'contacto.ending.subheader': '웹훅이 보고서를 생성하고 구성되면 캡처된 이메일로 보낼 것입니다.',
    'contacto.email.label': '이메일',
    'contacto.email.cta': '작성 →',
    'contacto.whatsapp.label': 'WhatsApp',
    'contacto.whatsapp.cta': '채팅 열기 →',
    'contacto.talia.label': 'Talia · 약속',
    'contacto.talia.cta': '작성 →',
    'contacto.agendar': '통화 예약',
    'contacto.closed.title': '진단 종료',
    'contacto.closed.desc': '업종, 설문 유형 및 자동화를 선택하기 위해 언제든지 다시 열 수 있습니다.',
    'contacto.closed.btn': '진단 열기',

    'sd.demo.survey.excellent': '매우 좋음',
    'sd.demo.survey.regular': '보통',
    'sd.demo.survey.bad': '나쁨',
    'sd.demo.survey.question': '질문',
    'sd.demo.survey.of': '/',
    'sd.demo.feature.1': '긴 양식 없음',
    'sd.demo.feature.2': '실시간 알림',
    'sd.demo.feature.3': '자동 일일 보고서',
    'sd.demo.feature.4': 'AI 패턴 감지',
    'sd.demo.alert.now': '지금',
    'sd.demo.alert.msg.negative': '부정적인 경험이 보고되었습니다',
    'sd.demo.alert.msg.positive': '만족한 고객',
    'sd.demo.alert.msg.neutral': '피드백 수신',
    'sd.demo.report.focus': '보고서 초점:',
    'sd.demo.report.seeks': '보고서가 찾는 것:',
    'sd.demo.report.case': '사례:',
    'sd.demo.report.analysis.negative': '불만 신호가 감지되었습니다. 운영 주제를 검토하세요.',
    'sd.demo.report.analysis.positive': '긍정적인 피드백. 잘 작동한 것을 식별하세요.',
    'sd.demo.report.analysis.neutral': '심각한 알림 없음. 추세를 계속 모니터링하세요.',
    'sd.demo.sentiment.positive': '긍정적',
    'sd.demo.sentiment.negative': '부정적',
    'sd.demo.sentiment.neutral': '중립',
    'sd.demo.report.priority.high': '높음',
    'sd.demo.report.priority.medium': '중간',
    'sd.demo.report.priority.low': '낮음',
    'sd.typing.1': '감정 분류 중...',
    'sd.typing.2': '태그 추출: 경험, 시간, 품질...',
    'sd.typing.3': '패턴 감지 중...',
    'sd.typing.4': '부정적인 응답에 대한 경고 생성 중...',
    'sd.typing.5': '보고서 컴파일 중...',
    'sd.liveform.section.label': '실제 양식',
    'sd.liveform.section.title': '어떤 흐름을 시도하고 싶으십니까?',
    'sd.liveform.section.desc': '이것은 유형, 보고서 및 Talia를 위한 이메일 템플릿과 함께 웹훅에 전송되는 실제 양식입니다.',
    'sd.liveform.window.title': '테스트 창',
    'sd.liveform.window.desc': '아래에서 흐름을 선택하면 여기에서 바로 열립니다. 다른 섹션으로 보내거나 사용자를 맥락에서 벗어나게 하지 않습니다.',
    'sd.liveform.close': '양식 닫기',
    'sd.liveform.diagnostico.label': '진단',
    'sd.liveform.diagnostico.title': '내 비즈니스를 위한 설문을 만들고 싶습니다',
    'sd.liveform.diagnostico.desc': '업종, 설문 유형, 채널 및 자동화를 묻습니다.',
    'sd.liveform.clientes.label': '고객',
    'sd.liveform.clientes.title': '서비스 후 설문',
    'sd.liveform.clientes.desc': '구매/약속 후 QR, WhatsApp 또는 링크용.',
    'sd.liveform.proyecto.label': '프로젝트',
    'sd.liveform.proyecto.title': '클라이언트 온보딩',
    'sd.liveform.proyecto.desc': '시스템 구축 전 맥락을 수집합니다.',
    'sd.liveform.eventos.label': '이벤트',
    'sd.liveform.eventos.title': 'RSVP / 확인',
    'sd.liveform.eventos.desc': '참석, 게스트, 선호도 및 후속 조치용.',
    'sd.liveform.staff.label': '직원',
    'sd.liveform.staff.title': '직원 평가',
    'sd.liveform.staff.desc': '성과, 분위기, 차단 요소 및 교육용.',
    'sd.liveform.cierre.label': '마감',
    'sd.liveform.cierre.title': '프로젝트 후 피드백',
    'sd.liveform.cierre.desc': 'NPS, 전달, 커뮤니케이션 및 두 번째 단계용.',

    'services.back': '뒤로',
    'services.title': '개별 서비스',
    'services.subtitle': '각 서비스는 독립적으로 계약하거나 월간 요금제의 일부로 계약할 수 있습니다. 모든 시스템은 귀하의 운영에 맞게 설계됩니다.',
    'services.discountNote': '* 출시 프로모션 · 다른 프로모션과 중복 불가 (예: 뉴스레터)',
    'services.cta.question': '찾는 것이 없으십니까? 모든 시스템은 귀하의 비즈니스에 적응합니다.',
    'services.cta.plans': '요금제 보기',
    'services.cta.whatsapp': 'WhatsApp 문의',

    // SurveyEngine
    'survey.welcome.badge': 'soul:23 Experience',
    'survey.required': '필수',
    'survey.back': '뒤로',
    'survey.next': '다음',
    'survey.submit': '제출',
    'survey.close': '닫기',
    'survey.progress': '진행 상황',
    'survey.restart': '설문 다시 시작',
    'survey.error.required': '이 답변은 필수입니다.',

    // Competency Evaluation
    'competencias.back': '뒤로',
    'competencias.label': '기술 평가',
    'competencias.titulo': '업종에 맞춰 적응하는 역량 평가',
    'competencias.subtitulo': '스마트 라우팅, 자동 채점, 카테고리별 보고서가 포함된 기술 평가 시스템. 작업자부터 엔지니어까지. 제조업부터 기술업까지.',
    'competencias.cta1': '견적 요청',
    'competencias.cta2': 'WhatsApp 문의',
    'competencias.industrias.titulo': '모든 업종용',
    'competencias.industrias.sub': '시스템이 귀하의 업종 기술 역량에 맞춰 적응합니다.',
    'competencias.niveles.titulo': '적응형 레벨',
    'competencias.niveles.sub': '역할과 경험에 따라 자동으로 배정되는 3가지 난이도 레벨.',
    'competencias.flujo.titulo': '작동 방식',
    'competencias.flujo.sub': '4단계 자동화 프로세스로 등록부터 임용 보고서까지.',
    'competencias.features.titulo': '시스템 기능',
    'competencias.features.sub': '기술 인재를 평가, 진단 및 개발하는 데 필요한 모든 것.',
    'competencias.reporte.titulo': '임용 보고서',
    'competencias.reporte.sub': '각 평가는 종합 점수, 카테고리 분석 및 개발 계획이 포함된 PDF를 생성합니다.',
    'competencias.integracion.titulo': '운영 시스템과 통합',
    'competencias.integracion.sub': 'CRM, ERP 또는 n8n 워크플로에 연결하여 결과가 필요한 곳으로 바로 흘러가도록 합니다.',
    'competencias.integracion.cta1': '데모 요청',
    'competencias.integracion.cta2': 'WhatsApp 문의',

    'competenciasHighlight.label': '새로운 시스템',
    'competenciasHighlight.titulo': 'AI 기반 역량 평가 시스템',
    'competenciasHighlight.sub': '역할과 경험에 따라 올바른 레벨을 할당하는 스마트 라우팅이 포함된 기술 평가 시스템. 자동 채점, 임용 PDF 보고서 및 카테고리 진단.',
    'competenciasHighlight.cta1': '시스템 보기',
    'competenciasHighlight.cta2': 'WhatsApp 문의',
    'competenciasHighlight.stat1': '적응형 레벨',
    'competenciasHighlight.stat2': '평가된 카테고리',
    'competenciasHighlight.stat3': '지원되는 산업',
    'competenciasHighlight.stat4Val': '자동',
    'competenciasHighlight.stat4': '자동 채점',
    'competenciasHighlight.preview.titulo': '보고서 미리보기',
    'competenciasHighlight.preview.sub': '평가 시스템의 예시 출력',
    'competenciasHighlight.preview.score': '종합 점수',
    'competenciasHighlight.preview.cats': '통과된 카테고리',
    'competenciasHighlight.preview.level': '중급',
    'competenciasHighlight.preview.levelLabel': '할당된 역량',
    'competenciasHighlight.preview.cat1': '기술 프로세스',
    'competenciasHighlight.preview.cat2': '산업 안전',
    'competenciasHighlight.preview.cat3': '문제 해결',
  },

  ZH: {
    'nav.como-funciona': '运作方式',
    'nav.servicios': '服务',
    'nav.demos': '演示',
    'nav.proyectos': '项目',
    'nav.precios': '价格',
    'nav.contacto': '联系',
    'nav.inicio': '首页',
    'nav.agendar': '预约咨询',
    'nav.competencias': '能力评估',
    'theme.dark': '深色',
    'theme.light': '浅色',

    'hero.titulo1': '您的业务可以',
    'hero.titulo2': '自主运行。',
    'hero.sub': '我们将您的预约、销售和运营连接到一个系统。您不再需要手动操作。您的业务开始自动运转。',
    'hero.btn1': '查看运作方式',
    'hero.btn2': '通过 WhatsApp 咨询',
    'hero.floating': 'vanity academy · dashboard · ia survey',
    'hero.img.soul23': 'soul:23',
    'hero.img.cursos': 'Vanity Academy 课程',
    'hero.img.dashboard': '运营仪表盘',
    'hero.img.sitio': 'Dra. DFG 网站',
    'hero.img.reporte': 'AI 调查报告',

    'problem.titulo': '您是否遇到这些问题…',
    'problem.sub': '您并不孤单。墨西哥大多数企业都是这样运营的：',
    'problem.1': '整天回复消息来安排预约',
    'problem.2': '手动计算才知道卖了多少',
    'problem.3': '不在店里就不知道生意状况',
    'problem.4': '员工迟到却没有任何记录',
    'problem.5': '客户取消预约却无法控制',
    'problem.cta': '这一切都可以改变。并没有你想的那么复杂。',
    'problem.img.flow': '自动化运营流程',
    'problem.img.mobile': '移动运营追踪',
    'problem.img.tools': '互联工作工具',

    'howitworks.titulo': '就这么简单',
    'howitworks.sub': '三大支柱。全部互联。您的业务自主运行。',
    'howitworks.step1.label': '第一步',
    'howitworks.step1.titulo': '自动预约',
    'howitworks.step1.desc': '客户通过 WhatsApp 预约。系统自动确认、发送提醒，客户取消时重新安排。您无需任何操作。',
    'howitworks.step2.label': '第二步',
    'howitworks.step2.titulo': '自动记录销售',
    'howitworks.step2.desc': '每笔付款自动保存。您随时了解销售额、销售人员和最 productive 的时段。无需计算。',
    'howitworks.step3.label': '第三步',
    'howitworks.step3.titulo': '手机上一目了然',
    'howitworks.step3.desc': '仪表盘实时显示业务状况。无论您在何处。无需依赖他人报告。',

    'tc.label': '40小时劳动改革',
    'tc.titulo': '员工工时',
    'tc.titulo2': '控制系统',
    'tc.desc': '新的40小时工作制改革要求精确记录员工工时。我们在您的企业安装系统——硬件、软件和支持——让您合规无忧。',
    'tc.btn1': '查看完整系统',
    'tc.btn2': '通过 WhatsApp 咨询',
    'tc.img': '员工工时控制仪表盘',
    'tc.licencias.titulo': '系统许可证',
    'tc.licencias.sub': '选择最适合您业务的方案。均包含软件、更新和基础支持。',
    'tc.plan1.nombre': '按月',
    'tc.plan1.sub': '/月',
    'tc.plan1.desc': '每月定期付款。适合无承诺开始。',
    'tc.plan2.nombre': '按季',
    'tc.plan2.sub': '/季',
    'tc.plan2.desc': '比月付节省约13%。每3个月结算。',
    'tc.plan3.nombre': '按半年',
    'tc.plan3.sub': '/半年',
    'tc.plan3.desc': '比月付节省约26%。每6个月结算。',
    'tc.plan4.nombre': '按年',
    'tc.plan4.sub': '/年',
    'tc.plan4.desc': '比月付节省约41%。一次性付款，无需操心。',
    'tc.especiales': '特殊项目单独报价 —',
    'tc.especiales.link': '申请报价',
    'tc.self.title': '自托管 · 您提供基础设施',
    'tc.self.desc': '如果您希望系统在自己的服务器上运行，您可以自行维护。无重复许可费用——仅需承担 VPS、设备和 AI 服务的预估年费 (~',
    'tc.self.tax': '可抵税 — 请咨询您的会计师。',

    'sd.label': '客户体验智能',
    'sd.titulo1': '正在流失的信息，',
    'sd.titulo2': '现在为您所用。',
    'sd.sub': '每一位默默离开的客户都是信息的流失。系统捕获这些反馈，进行结构化处理，发送到 webhook 生成报告和可操作的警报。',
    'sd.problema.label': '问题',
    'sd.problema.titulo': '未被收集的反馈会怎样？',
    'sd.problema.desc': '90% 的不满客户会默默离开。没有数据就无法改进。没有反馈就会重复同样的错误。',
    'sd.solucion.label': '解决方案',
    'sd.solucion.titulo': '捕获流失信息的 AI 代理',
    'sd.ai1.titulo': '情感分析',
    'sd.ai1.desc': '自动将每条回复分类为积极、中性或消极。',
    'sd.ai2.titulo': '智能标签',
    'sd.ai2.desc': '提取关键主题：质量、时间、价格、服务、人员。',
    'sd.ai3.titulo': '模式检测',
    'sd.ai3.desc': '识别趋势："周五投诉更多"，"X 服务评价最高"。',
    'sd.ai4.titulo': '实时警报',
    'sd.ai4.desc': '出现问题立即知晓。无需手动查看调查问卷。',
    'sd.flow.label': '数据流程',
    'sd.flow1': '二维码 / 链接',
    'sd.flow1.desc': '客户扫码或通过 WhatsApp 接收链接',
    'sd.flow2': '30秒问卷',
    'sd.flow2.desc': '回答 3-4 个简单问题，零摩擦',
    'sd.flow3': 'AI 处理',
    'sd.flow3.desc': '分析情感、检测标签、识别模式',
    'sd.flow4': '结构化数据',
    'sd.flow4.desc': '每个回答转化为可操作数据',
    'sd.flow5': '报告 / 警报',
    'sd.flow5.desc': '每日仪表盘 + 即时警报辅助决策',
    'sd.demo.intro': '体验系统',
    'sd.demo.intro.desc': '花 30 秒像客户一样回答。AI 即刻完成分析。',
    'sd.demo.btn': '开始演示',
    'sd.demo.analyzing': '正在准备报告',
    'sd.demo.alert.label': '即时警报',
    'sd.demo.alert.title': '检测到不满客户',
    'sd.demo.alert.info': '这是企业主收到的警报',
    'sd.demo.alert.sub': '手机即时接收。无需打开平台。',
    'sd.demo.alert.btn': '查看完整报告',
    'sd.demo.report.card': 'soul:23 反馈报告',
    'sd.demo.report.sub': '使用模拟回复生成的示例报告',
    'sd.demo.report.title': '分析摘要',
    'sd.demo.report.priority': '优先级',
    'sd.demo.report.responses': '回复',
    'sd.demo.report.alerts': '警报',
    'sd.demo.report.tags': '检测标签',
    'sd.demo.report.sentiment': '总体情感',
    'sd.demo.report.topic': '首要话题',
    'sd.demo.report.footer': 'Powered by soul:23 · AI 自动化反馈',
    'sd.demo.report.btn': '再次体验',
    'sd.stats1.val': '90%',
    'sd.stats1.label': '的反馈因没有此系统而流失',
    'sd.stats2.val': '30秒',
    'sd.stats2.label': '平均问卷时间',
    'sd.stats3.val': '24/7',
    'sd.stats3.label': '自动化数据采集',
    'sd.cta': '我需要这个系统',
    'sd.cta.sub': '兼容任何行业：餐厅、水疗中心、诊所、商店、学校',

    'proyectos.titulo': '已经自主运营的企业',
    'proyectos.sub': '像您一样的企业的真实案例。',

    'testimonios.titulo': '用户评价',

    'contacto.titulo': '告诉我们您的情况',
    'contacto.sub': '回答迷你诊断。Webhook 接收完整数据，包含表单类型和可直接使用的信息。',
    'contacto.habla': '联系我们',

    'footer.tagline': '让您的业务自主运行的系统。',
    'footer.servicios': '服务',
    'footer.planes': '价格',
    'footer.privacidad': '隐私',
    'footer.reembolso': '退款',
    'footer.terminos': '条款',
    'footer.copyright': '© 2026 · soul:23',

    'proyectos.status.adjusting': '审核中',

    'testimonios.0.text': '我需要我的页面真正传达我所做的事情，因为之前一切都感觉很冰冷。现在我的患者进来，看到治疗的内容，并预订他们的预约，而我不需要来回发送消息。一切都感觉更加专业和有条理，但最重要的是它减轻了我管理上的负担。',
    'testimonios.0.name': 'Gloria',
    'testimonios.0.business': '治疗师',
    'testimonios.1.text': '说实话，之前我被笔记本和纸质日程表搞得发疯；在三个分店之间一团糟。最改变我生活的是停止手动做女孩们的工资，不再不得不追逐每日销售额。现在一切自动计算，我终于知道死时间是怎么回事，而不必粘在那里。',
    'testimonios.1.name': 'Alejandra',
    'testimonios.1.business': '美容院',
    'testimonios.2.text': '我想要的是停止浪费时间审查我甚至不理解的调查平台。现在预订自动进来，客户所说的直接到达我的手机。我和我的团队不再需要猜测；我们在那一刻就有信息。我节省了很多来回，系统处理一切。',
    'testimonios.2.name': 'Roberto Pérez',
    'testimonios.2.business': '餐厅',

    'contacto.config.name': '迷你诊断调查',
    'contacto.config.welcome.headline': '告诉我们您想测量什么',
    'contacto.config.welcome.subheader': '根据您的回答，我们为您的电子邮件构建第一份报告，并查看是否有必要通话。',
    'contacto.config.welcome.buttonLabel': '开始',
    'contacto.q.tipo_negocio.headline': '首先：您的企业属于哪个行业？',
    'contacto.q.tipo_negocio.subheader': '这会改变语言、指标和适合使用的问题。',
    'contacto.q.tipo_encuesta.headline': '现在选择您想运行什么类型的调查',
    'contacto.q.tipo_encuesta.subheader': '您可以选择多个。这将作为完整选择发送到 webhook 以生成电子邮件和报告。',
    'contacto.q.nombre.headline': '您叫什么名字？',
    'contacto.q.nombre.placeholder': '您的姓名',
    'contacto.q.negocio.headline': '您的企业叫什么名字？',
    'contacto.q.negocio.placeholder': '企业名称',
    'contacto.q.email.headline': '我们应该将报告发送到哪个电子邮件？',
    'contacto.q.email.placeholder': 'email@example.com',
    'contacto.q.email.validation': '电子邮件地址无效。',
    'contacto.q.telefono.headline': '您的 WhatsApp？',
    'contacto.q.telefono.placeholder': '8441234567',
    'contacto.q.telefono.validation': '必须在 10 到 13 位数字之间。',
    'contacto.q.canal.headline': '您想在哪里收集回复？',
    'contacto.q.audiencia.headline': '谁会回答那个调查？',
    'contacto.q.audiencia.subheader': '这有助于电子邮件听起来不通用，并使用正确的上下文。',
    'contacto.q.momento.headline': '您想什么时候请求回复？',
    'contacto.q.momento.subheader': '时间点定义自动化、提醒和警报。',
    'contacto.q.necesidad.headline': '回复后应该发生什么？',
    'contacto.q.urgencia.headline': '您希望什么时候运行？',
    'contacto.q.decision.headline': '您想用这些回复做出什么决定？',
    'contacto.q.decision.subheader': '示例：了解他们为什么取消，什么课程卖得更多，哪个员工需要支持。',
    'contacto.q.decision.placeholder': '我想决定...',
    'contacto.q.pregunta_clave.headline': '您脑海中挥之不去的问题是什么？',
    'contacto.q.pregunta_clave.subheader': '我们将用它作为客户收到的报告的中心。',
    'contacto.q.pregunta_clave.placeholder': '我需要知道是否...',
    'contacto.q.alerta_critica.headline': '什么回复应该触发立即警报？',
    'contacto.q.alerta_critica.subheader': '示例：糟糕的服务、取消、严重投诉、超负荷的员工、紧急线索。',
    'contacto.q.alerta_critica.placeholder': '如果有人回答则警报...',
    'contacto.q.descripcion.headline': 'Talia 还需要知道什么来个性化报告？',
    'contacto.q.descripcion.subheader': '运营背景、分支机构、规模、当前问题或您目前如何收集反馈。',
    'contacto.q.descripcion.placeholder': '今天我们是这样做的...',
    'contacto.ending.headline': '我们收到了您的诊断',
    'contacto.ending.subheader': 'Webhook 将生成报告并在配置完成后将其发送到捕获的电子邮件。',
    'contacto.email.label': '电子邮件',
    'contacto.email.cta': '写信 →',
    'contacto.whatsapp.label': 'WhatsApp',
    'contacto.whatsapp.cta': '打开聊天 →',
    'contacto.talia.label': 'Talia · 预约',
    'contacto.talia.cta': '写信 →',
    'contacto.agendar': '预约通话',
    'contacto.closed.title': '诊断已关闭',
    'contacto.closed.desc': '您可以随时重新打开它以选择行业、调查类型和自动化。',
    'contacto.closed.btn': '打开诊断',

    'sd.demo.survey.excellent': '优秀',
    'sd.demo.survey.regular': '一般',
    'sd.demo.survey.bad': '差',
    'sd.demo.survey.question': '问题',
    'sd.demo.survey.of': '/',
    'sd.demo.feature.1': '无长表单',
    'sd.demo.feature.2': '实时警报',
    'sd.demo.feature.3': '自动每日报告',
    'sd.demo.feature.4': 'AI 模式检测',
    'sd.demo.alert.now': '现在',
    'sd.demo.alert.msg.negative': '报告了负面体验',
    'sd.demo.alert.msg.positive': '满意的客户',
    'sd.demo.alert.msg.neutral': '已收到反馈',
    'sd.demo.report.focus': '报告聚焦于',
    'sd.demo.report.seeks': '报告寻求',
    'sd.demo.report.case': '案例：',
    'sd.demo.report.analysis.negative': '检测到不满信号。审查运营主题。',
    'sd.demo.report.analysis.positive': '积极反馈。确定哪些做得好。',
    'sd.demo.report.analysis.neutral': '无严重警报。继续监控趋势。',
    'sd.demo.sentiment.positive': '积极',
    'sd.demo.sentiment.negative': '消极',
    'sd.demo.sentiment.neutral': '中性',
    'sd.demo.report.priority.high': '高',
    'sd.demo.report.priority.medium': '中',
    'sd.demo.report.priority.low': '低',
    'sd.typing.1': '分类情感...',
    'sd.typing.2': '提取标签：体验、时间、质量...',
    'sd.typing.3': '检测模式...',
    'sd.typing.4': '为负面回复生成警报...',
    'sd.typing.5': '编译报告...',
    'sd.liveform.section.label': '真实表单',
    'sd.liveform.section.title': '选择您想尝试哪个流程。',
    'sd.liveform.section.desc': '这些是将通过其类型、报告和 Talia 的电子邮件模板发送到 webhook 的实际表单。',
    'sd.liveform.window.title': '测试窗口',
    'sd.liveform.window.desc': '从下方选择一个流程，它将在此处打开，而不会将您发送到其他部分或让用户脱离上下文。',
    'sd.liveform.close': '关闭表单',
    'sd.liveform.diagnostico.label': '诊断',
    'sd.liveform.diagnostico.title': '我想为我的企业创建一个调查',
    'sd.liveform.diagnostico.desc': '询问行业、调查类型、渠道和自动化。',
    'sd.liveform.clientes.label': '客户',
    'sd.liveform.clientes.title': '服务后调查',
    'sd.liveform.clientes.desc': '用于购买/预约后的 QR、WhatsApp 或链接。',
    'sd.liveform.proyecto.label': '项目',
    'sd.liveform.proyecto.title': '客户入职',
    'sd.liveform.proyecto.desc': '在构建系统之前收集背景信息。',
    'sd.liveform.eventos.label': '活动',
    'sd.liveform.eventos.title': 'RSVP / 确认',
    'sd.liveform.eventos.desc': '用于出席、客人、偏好和跟进。',
    'sd.liveform.staff.label': '员工',
    'sd.liveform.staff.title': '员工评估',
    'sd.liveform.staff.desc': '用于绩效、氛围、障碍和培训。',
    'sd.liveform.cierre.label': '关闭',
    'sd.liveform.cierre.title': '项目后反馈',
    'sd.liveform.cierre.desc': '用于 NPS、交付、沟通和第二阶段。',

    'services.back': '返回',
    'services.title': '单项服务',
    'services.subtitle': '每项服务可单独购买，也可作为月度计划的一部分。所有系统均根据您的业务量身定制。',
    'services.discountNote': '* 首发优惠 · 不可与其他优惠叠加（例如：通讯订阅）',
    'services.cta.question': '找不到您需要的服务？每个系统都可以根据您的业务定制。',
    'services.cta.plans': '查看方案',
    'services.cta.whatsapp': '通过 WhatsApp 咨询',

    // SurveyEngine
    'survey.welcome.badge': 'soul:23 Experience',
    'survey.required': '必填',
    'survey.back': '返回',
    'survey.next': '下一步',
    'survey.submit': '提交',
    'survey.close': '关闭',
    'survey.progress': '进度',
    'survey.restart': '重新启动调查',
    'survey.error.required': '此回答是必填项。',

    // Competency Evaluation
    'competencias.back': '返回',
    'competencias.label': '技术评估',
    'competencias.titulo': '适应您行业的能力评估',
    'competencias.subtitulo': '具备智能路由、自动评分和分类报告的技术评估系统。从操作员到工程师。从制造业到科技业。',
    'competencias.cta1': '获取报价',
    'competencias.cta2': '通过 WhatsApp 咨询',
    'competencias.industrias.titulo': '适用于任何行业',
    'competencias.industrias.sub': '系统适应您行业的技术能力，而不是反过来。',
    'competencias.niveles.titulo': '自适应级别',
    'competencias.niveles.sub': '根据角色和经验自动分配的三种难度级别。',
    'competencias.flujo.titulo': '运作方式',
    'competencias.flujo.sub': '通过4个自动化步骤，从注册到执行报告。',
    'competencias.features.titulo': '系统功能',
    'competencias.features.sub': '评估、诊断和发展技术人才所需的一切。',
    'competencias.reporte.titulo': '执行报告',
    'competencias.reporte.sub': '每次评估都会生成一份包含总分、类别分析和发展计划的 PDF。',
    'competencias.integracion.titulo': '与您的运营集成',
    'competencias.integracion.sub': '我们将系统连接到您的 CRM、ERP 或 n8n 流程，以便结果直接流向您需要的地方。',
    'competencias.integracion.cta1': '请求演示',
    'competencias.integracion.cta2': '通过 WhatsApp 交谈',

    'competenciasHighlight.label': '新系统',
    'competenciasHighlight.titulo': 'AI 驱动的能力评估系统',
    'competenciasHighlight.sub': '具备智能路由的技术评估系统，可根据角色和经验分配正确的级别。自动评分、执行 PDF 报告和类别诊断。',
    'competenciasHighlight.cta1': '查看系统',
    'competenciasHighlight.cta2': '通过 WhatsApp 咨询',
    'competenciasHighlight.stat1': '自适应级别',
    'competenciasHighlight.stat2': '评估的类别',
    'competenciasHighlight.stat3': '支持的行业',
    'competenciasHighlight.stat4Val': '自动',
    'competenciasHighlight.stat4': '自动评分',
    'competenciasHighlight.preview.titulo': '报告预览',
    'competenciasHighlight.preview.sub': '评估系统的示例输出',
    'competenciasHighlight.preview.score': '总分',
    'competenciasHighlight.preview.cats': '通过的类别',
    'competenciasHighlight.preview.level': '中级',
    'competenciasHighlight.preview.levelLabel': '分配的能力',
    'competenciasHighlight.preview.cat1': '技术流程',
    'competenciasHighlight.preview.cat2': '工业安全',
    'competenciasHighlight.preview.cat3': '问题解决',
  },
}

mergeSurveyTranslations(dict)

interface LanguageContextType {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
  toggle: () => void
}

const LanguageContext = createContext<LanguageContextType | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('ES')

  const toggle = () => setLang(l => {
    const idx = langs.indexOf(l)
    return langs[(idx + 1) % langs.length]
  })

  const t = (key: string): string => dict[lang][key] || key

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggle }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider')
  return ctx
}
